#!/bin/bash

ifc=$(ifconfig | grep -woP "(en|eth)(\d|[a-zA-Z])+:" | grep -woP "(en|eth)(\d|[a-zA-Z])+")

if [[ "$ifc" != "" ]]; then
  status=$(cat /sys/class/net/"$ifc"/operstate)
  ip=""

  case $status in
    "up")
      colour="cyan"
      ifcip=$(ifconfig "$ifc" | grep -P "inet (\d+\.\d+\.\d+\.\d+)" -wo | grep -P "\d+\.\d+\.\d+\.\d+" -wo)
    
      if [[ $ifcip != "" ]]; then
        ip=" @ $ifcip"
      fi;;
    "down") colour="orange";;
  esac
  echo "<span foreground='$colour'>$status</span>$ip"
fi
