#!/bin/bash

ifc=$(ip addr | grep -woP "(eno|eth)\d+(\d|[a-zA-Z])*" | head -n1)

if [[ "$ifc" != "" ]]; then
  status=$(cat /sys/class/net/$ifc/operstate)
  ip=""

  case $status in
    "up")
      colour="cyan"
      ifcip=$(ip addr show dev $ifc | grep -P "inet (\d+\.\d+\.\d+\.\d+)" -wo | grep -P "\d+\.\d+\.\d+\.\d+" -wo)
    
      if [[ $ifcip != "" ]]; then
        ip=" @ $ifcip"
      fi;;
    "down") colour="orange";;
  esac
  echo "<span foreground='$colour'>$status</span>$ip"
fi
