#!/bin/bash

meminfo=$(cat /proc/meminfo)
IFS=";" read -r -a keys <<< $BLOCK_INSTANCE
key1=${keys[0]}

if [[ ${#keys[@]} -le 0 ]]; then
  key2=""
else
  key2=${keys[1]}
fi

val1=$(echo "$meminfo" | grep -i "$key1" | awk -F ':' '{print $2}' | tr -d " kB")
fullval1=$val1

size1="KB"
colour="light green"
if [[ $val1 -gt 1024 ]]; then
  size1="MB"
  val1=$(expr $val1 / 1024)
fi
if [[ $val1 -gt 1024 ]]; then
  size1="GB"
  val1=$(expr $val1 / 1024)
fi
if [[ "$key2" != "" ]]; then
  val2=$(echo "$meminfo" | grep -i "$key2" | awk -F ':' '{print $2}' | tr -d " kB")
  fullval2=$val2

  size2="KB"
  if [[ $val2 -gt 1024 ]]; then
    size2="MB"
    val2=$(expr $val2 / 1024)
  fi
  if [[ $val2 -gt 1024 ]]; then
    size2="GB"
    val2=$(expr $val2 / 1024)
  fi

  if [[ $fullval1 -le $(expr $fullval2 / 10) ]]; then
    colour="red"
  fi

  span="<span foreground='$colour'>"
  echo "$span$val1 $size1</span> / $val2 $size2"
else
  echo "$val1 $size1"
fi
