#!/bin/bash

battery=$BLOCK_INSTANCE
battery_info=$(acpi -b | grep "Battery $battery")
if [[ $battery_info = *"No support"* ]]; then
	exit 0
fi
state=$(echo "$battery_info" | grep -wo "Full\|Charging\|Discharging")
power=$(echo "$battery_info" | grep -o '[0-9]\+%' | tr -d '%')
strength=$(expr $power / 10)

low_value=2
colour="light green"

if [[ "$strength" != "" ]]; then

    case $strength in
      1) bars="/----";;
      2) bars="/----";;
      3) bars="//---";;
      4) bars="//---";;
      5) bars="///--";;
      6) bars="///--";;
      7) bars="////-";;
      8) bars="////-";;
      9) bars="/////";;
      10) bars="/////";;
      *)
        bars="-----"
        colour="orange";;
    esac
    if [[ "$strength" -le "$low_value" ]]; then
      colour="red"
    fi
    if [[ "$state" == "Charging" ]]; then
	power="⚡ $power"
    fi
    echo "[<span foreground='$colour'>$bars</span>] $power%"
fi
