#!/bin/bash

usage=$(free | grep Mem | awk '{ print(int($3/$2 * 100.0)) }')
scaled=$(echo $usage | awk '{ print(int($1/10)) }')
colour="light green"
    case $scaled in
      0) bars="/----";;
      1) bars="/----";;
      2) bars="//---";;
      3) bars="//---";;
      4) bars="///--";;
      5) bars="///--";;
      6) bars="///--";;
      7) bars="////-";;
      8) bars="////-";;
      9) bars="/////";;
      10) bars="/////";;
    esac
    if [[ "$scaled" -ge 8 ]]; then
      colour="orange"
    fi
    echo "[<span foreground='$colour'>$bars</span>] $usage%"
